"""Initial migration

Revision ID: 2640760468e4
Revises: 
Create Date: 2023-05-25 17:35:16.516212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2640760468e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_on', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('phoneNumber', sa.String(length=21), nullable=False),
    sa.Column('country', sa.String(length=25), nullable=False),
    sa.Column('date_registered', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('innovations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=60), nullable=False),
    sa.Column('video_link', sa.String(length=60), nullable=False),
    sa.Column('created_on', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('innovations')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
